### ISSUE TITLE
Add COC

### ISSUE THREAD

**Issue by sckott** [pdxrconf/pdxrconf.github.io#1]

**Comment by okeyes-r7** [comment]
Do you have one already written or would you like me to adapt one of the standard ones?

**Comment by sckott** [comment]
Don't have one already. Adapting a standard one sounds good.

**Comment by Ironholds** [comment]
Who's going to be enforcing it/what are the enforcement policies?

**Comment by sckott** [comment]
Seems like many COC's I've looked at say enforcement by "the organizers", though it's probably good to give a specific person as the go to, can be me (email: pdxrlang@gmail.com) . Thoughts?

**Comment by Ironholds** [comment]
Re: the meeting yesterday, I really like @lwinfree 's suggestion of https://blog.pydx.org/code-of-conduct/ - so, email, phone number, training for the organisers.

**Comment by Ironholds** [comment]
I'm gonna integrate this tomorrow if nobody else has the time. What email/phone number?

**Comment by lwinfree** [comment]
Thx!

Phone numbers:
432-230-0488 (lilly)
713-364-5048 (Scott)
503-975-7799
605-484-7066
503-481-8470

Do you think we should put the name of the person with their phone #? or just list the numbers?
