### ISSUE TITLE
FAQ for 2019 Site has 2018 Content

### ISSUE THREAD

**Issue by davidski** [pdxrconf/pdxrconf.github.io#32]
The FAQ at https://cascadiarconf.com/faq/ still refers to the 2018 PDX edition. I'm super time bound these days, so if someone gets to this before me, that would be terrific!

**Comment by sckott** [comment]
Thanks @davidski can get to it in Monday

**Comment by sckott** [comment]
@thebioengineer i just udpated the FAQ page with details i know for this year https://cascadiarconf.com/faq/ - can you at some point fill in details for: 

- What about food?
- Will you provide lunch?
- Will talks be recorded?
- Will there be a lactation room?
- travel: bike, train, walking, car, flying

**Comment by sckott** [comment]
done
