### ISSUE TITLE
Ban list?

### ISSUE THREAD

**Issue by Ironholds** [pdxrconf/pdxrconf.github.io#4]
Re the CoC: we should probably put together (or at least entertain) a list of 'programmery people who might attend but will be blocked if they try because they're an active risk'. It provides a resource we can append the perpetrators of any incidents to, and then pass on to future conferences in this space.

**Comment by sckott** [comment]
Good idea. Sounds good to me. Is that a public thing?  Private?

**Comment by Ironholds** [comment]
Usually they're private and handled within the organising committee, and can then be passed on to successive committees and confs. I've got a few names (mostly general programming people, not R specific, but you never know) if you wanna spin up a thread.

**Comment by sckott** [comment]
Sounds good, want to join our slack ? i'll invite if yes

**Comment by Ironholds** [comment]
Go for it!

**Comment by sckott** [comment]
sent 📫

**Comment by Ironholds** [comment]
Done!
