### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by thebioengineer** [pdxrconf/pdxrconf.github.io#86]
Would it be possible to add this PNG for the schedule for folks? I figure this would be easier than having to write up the HTML!

https://drive.google.com/file/d/1R62SiUhbby7PWnt1nEidgMikjwNThAyo/view?usp=sharing

**Comment by k8hertweck** [comment]
@thebioengineer Could you share the (read-only) link to the spreadsheet?

**Comment by thebioengineer** [comment]
https://docs.google.com/spreadsheets/d/1xlx_jnsNM6C2qckinhxoGKJ9Mn9mqXckyWRL5KQXKQo/edit?usp=sharing
